-- AlterTable
ALTER TABLE "order_invoices" ALTER COLUMN "access_key" DROP NOT NULL,
ALTER COLUMN "serial" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "shipping_company_name" DROP NOT NULL,
ALTER COLUMN "gross_weight" DROP NOT NULL,
ALTER COLUMN "net_weight" DROP NOT NULL,
ALTER COLUMN "discount_percentage" DROP NOT NULL,
ALTER COLUMN "quantity" DROP NOT NULL,
ALTER COLUMN "product_value" DROP NOT NULL,
ALTER COLUMN "additional_value" DROP NOT NULL,
ALTER COLUMN "shipping_value" DROP NOT NULL,
ALTER COLUMN "insurance_value" DROP NOT NULL,
ALTER COLUMN "ipi_value" DROP NOT NULL,
ALTER COLUMN "total_value" DROP NOT NULL,
ALTER COLUMN "transaction_branch_code" DROP NOT NULL,
ALTER COLUMN "transaction_date" DROP NOT NULL,
ALTER COLUMN "transaction_code" DROP NOT NULL,
ALTER COLUMN "issue_date" DROP NOT NULL,
ALTER COLUMN "package_number" DROP NOT NULL;
